from ..categories import *
from .group import Group


class All(Group):
    _name = "all"
    _categories = [
        Adjective,
        Animal,
        Atmosphere,
        Author,
        Bird,
        Book,
        Brand,
        Bread,
        Cake,
        Capital,
        Cheese,
        City,
        Clothing,
        Color,
        Condiment,
        Constellation,
        Country,
        Cuisine,
        Currency,
        Curry,
        Dog,
        Drink,
        Electronic,
        Element,
        Emotion,
        Fabric,
        Festivals,
        Film,
        Fish,
        Flower,
        Food,
        Fruit,
        Gem,
        Geography,
        Greek,
        GreekGod,
        Insect,
        Instrument,
        Language,
        Music,
        OperatingSystem,
        Particle,
        Pasta,
        Planet,
        Pokemon,
        Profession,
        ProgrammingLanguage,
        RandomId,
        Reptile,
        Scientist,
        SearchEngine,
        Shape,
        Spice,
        Sport,
        State,
        Tea,
        Tool,
        Utensil,
        Vegetable,
        Vehicle,
        Weather,
        Wine,
        Zodiac,
    ]
