from ..categories import *
from .group import Group


class All(Group):
    _name = "all"
    _categories = [
        Adjective,
        Animal,
        Atmosphere,
        Bird,
        Bread,
        Building,
        Cake,
        Capital,
        Cheese,
        City,
        Clothing,
        Coffee,
        Color,
        Condiment,
        Constellation,
        Country,
        Cuisine,
        Currency,
        Curry,
        Dog,
        Drink,
        Electronic,
        Element,
        Emotion,
        Fabric,
        Festival,
        Fish,
        Flavour,
        Flower,
        Food,
        Fruit,
        Gem,
        Geography,
        Greek,
        GreekGod,
        Insect,
        Instrument,
        Language,
        Music,
        Myth,
        Particle,
        Pasta,
        Planet,
        Pokemon,
        Profession,
        RandomId,
        Reptile,
        Shape,
        Spice,
        Sport,
        State,
        Tea,
        Time,
        Tool,
        Utensil,
        Vegetable,
        Vehicle,
        Weather,
        Wine,
        Zodiac,
    ]
