from ..category import Category


class Animal(Category):
    def get_values(self):
        return [
            "ant",
            "axolotl",
            "bat",
            "bear",
            "bird",
            "bobcat",
            "buffalo",
            "butterfly",
            "cat",
            "centipede",
            "cockroach",
            "cow",
            "coyote",
            "deer",
            "dog",
            "dolphin",
            "duck",
            "eagle",
            "elephant",
            "fox",
            "frog",
            "gecko",
            "goat",
            "hamster",
            "hippopotamus",
            "kangaroo",
            "koala",
            "leopard",
            "lion",
            "lizard",
            "lobster",
            "monkey",
            "otter",
            "oyster",
            "parrot",
            "puma",
            "rabbit",
            "raccoon",
            "salamander",
            "shark",
            "shrimp",
            "skunk",
            "snake",
            "squirrel",
            "swan",
            "tiger",
            "trout",
            "turkey",
            "turtle",
            "whale",
            "zebra"
        ]
