from ..category import Category


class Bird(Category):
    _name = "bird"
    _values = [
        "blackbird",
        "bluebird",
        "bluejay",
        "buzzard",
        "canary",
        "chaffinch",
        "chicken",
        "cockatoo",
        "condor",
        "crane",
        "crow",
        "dove",
        "eagle",
        "egret",
        "emu",
        "falcon",
        "finch",
        "flamingo",
        "goldfinch",
        "goose",
        "grouse",
        "hawk",
        "heron",
        "hummingbird",
        "ibis",
        "jackdaw",
        "kestrel",
        "kingfisher",
        "lark",
        "lovebird",
        "macaw",
        "magpie",
        "mockingbird",
        "nightingale",
        "ostrich",
        "owl",
        "parrot",
        "partridge",
        "peacock",
        "pelican",
        "penguin",
        "pheasant",
        "pigeon",
        "puffin",
        "quail",
        "raven",
        "robin",
        "seagull",
        "skylark",
        "sparrow",
        "sparrowhawk",
        "starling",
        "stork",
        "swallow",
        "swan",
        "thrush",
        "toucan",
        "turkey",
        "vulture",
        "woodpecker",
        "wren",
    ]
