from ..category import Category


class Brand(Category):
    _name = "brand"
    _values = [
        "adidas",
        "airtel",
        "amazon",
        "apple",
        "audi",
        "bmw",
        "bush",
        "cisco",
        "dyson",
        "facebook",
        "flora",
        "ford",
        "gillette",
        "google",
        "hisense",
        "honda",
        "ikea",
        "infiniti",
        "intel",
        "microsoft",
        "netflix",
        "nike",
        "nissan",
        "nokia",
        "nvidia",
        "oppo",
        "oracle",
        "paypal",
        "puma",
        "reebok",
        "reliance",
        "samsung",
        "sandisk",
        "sap",
        "sony",
        "tesla",
        "toyota",
        "ups",
        "vizio",
        "xiaomi",
        "xoom",
    ]
