from .category import Category


class Building(Category):
    _name = "building"
    _values = [
        "airport",
        "amphitheater",
        "asylum",
        "basilica",
        "bathhouse",
        "boathouse",
        "brewery",
        "bungalow",
        "castle",
        "cathedral",
        "chateau",
        "church",
        "cinema",
        "college",
        "cottage",
        "courthouse",
        "embassy",
        "factory",
        "gallery",
        "greenhouse",
        "hospital",
        "hotel",
        "library",
        "lighthouse",
        "market",
        "monastery",
        "museum",
        "pagoda",
        "prison",
        "restaurant",
        "school",
        "skyscraper",
        "supermarket",
        "temple",
        "theater",
        "villa",
        "warehouse",
        "windmill",
    ]
