from ..category import Category


class City(Category):
    def get_values(self):
        return[
            'Tokyo',
            'Delhi',
            'Shanghai',
            'SaoPaulo',
            'MexicoCity',
            'Cairo',
            'Mumbai',
            'Beijing',
            'Dhaka',
            'Osaka',
            'NewYork',
            'Karachi',
            'BuenosAires',
            'Istanbul',
            'Kolkata',
            'Manila',
            'Lagos',
            'RioDeJaneiro',
            'LosAngeles',
            'Moscow',
            'Paris',
            'Jakarta',
            'Bangkok',
            'Seoul',
            'London',
            'Toronto',
            'Berlin',
            'Madrid',
            'Seattle',
            'SanFrancisco',
            'Ankara',
            'Riyadh',
            'Male',
            'PortLouis',
            'Skopje',
            'Reykjavik',
            'Jerusalem',
            'Dublin',
            'Edinburgh',
            'Cardiff',
            'Ottawa',
            'Munich',
            'Belgrade',
            'Prague',
            'Bern'
        ]
