from ..category import Category


class City(Category):
    def get_values(self):
        return [
            "ankara",
            "bangkok",
            "beijing",
            "belgrade",
            "berlin",
            "bern",
            "cairo",
            "cardiff",
            "delhi",
            "dhaka",
            "dublin",
            "edinburgh",
            "istanbul",
            "jakarta",
            "jerusalem",
            "karachi",
            "kolkata",
            "lagos",
            "london",
            "madrid",
            "male",
            "manila",
            "milan",
            "moscow",
            "mumbai",
            "munich",
            "osaka",
            "ottawa",
            "paris",
            "prague",
            "riyadh",
            "rome",
            "seattle",
            "seoul",
            "shanghai",
            "skopje",
            "tokyo",
            "toronto",
            "venice",
        ]
