from ..category import Category


class Color(Category):
    _name = "color"
    _values = [
        "amber",
        "apricot",
        "aquamarine",
        "azure",
        "beige",
        "black",
        "blue",
        "bronze",
        "brown",
        "burgundy",
        "byzantium",
        "cerulean",
        "coral",
        "cyan",
        "erin",
        "gold",
        "green",
        "grey",
        "indigo",
        "ivory",
        "jade",
        "lilac",
        "lime",
        "magenta",
        "ochre",
        "olive",
        "orange",
        "plum",
        "purple",
        "raspberry",
        "red",
        "rose",
        "ruby",
        "salmon",
        "sangria",
        "sapphire",
        "scarlet",
        "silver",
        "tan",
        "taupe",
        "teal",
        "turquoise",
        "ultamarine",
        "violet",
        "viridian",
        "white",
        "yellow",
    ]
