from ..category import Category


class Color(Category):
    def get_values(self):
        return[
            'black',
            'red',
            'blue',
            'green',
            'white',
            'grey',
            'yellow',
            'brown',
            'orange',
            'purple',
            'amber',
            'magenta',
            'beige',
            'bronze',
            'burgundy',
            'cerulean',
            'indigo',
            'violet',
            'scarlet',
            'teal',
            'taupe',
            'silver',
            'gold',
            'ruby',
            'rose',
            'plum',
            'sapphire',
            'salmon',
            'sangria',
            'viridian',
            'tan',
            'ochre',
            'lilac',
            'lime',
            'ivory',
            'jade',
            'erin',
            'coral',
            'byzantium',
            'apricot',
            'azure',
            'aquamarine',
            'turquoise',
            'ultamarine',
            'cyan',
            'olive',
            'raspberry'
        ]
