from ..category import Category


class Country(Category):
    def get_values(self):
        return [
            'India',
            'China',
            'Nepal',
            'Japan',
            'Pakistan',
            'France',
            'Austria',
            'Bahamas',
            'Australia',
            'Bulgaria',
            'Burundi',
            'Canada',
            'Chile',
            'Fiji',
            'Ethiopia',
            'Finland',
            'Guyana',
            'Iceland',
            'Ireland',
            'Egypt',
            'Sudan',
            'Syria',
            'Bahrain',
            'Qatar',
            'Estonia',
            'Russia',
            'Germany',
            'Netherlands',
            'Yugoslavia',
            'Serbia',
            'Romania',
            'Poland',
            'Moldova',
            'Hungary',
            'Belgium',
            'Switzerland',
            'Austria',
            'Greece'
        ]
