from .category import Category


class Country(Category):
    _name = "country"
    _values = [
        "australia",
        "austria",
        "bahamas",
        "bahrain",
        "belgium",
        "bulgaria",
        "burundi",
        "canada",
        "chile",
        "china",
        "egypt",
        "estonia",
        "ethiopia",
        "fiji",
        "finland",
        "france",
        "germany",
        "greece",
        "guyana",
        "hungary",
        "iceland",
        "india",
        "ireland",
        "japan",
        "moldova",
        "nepal",
        "netherlands",
        "pakistan",
        "poland",
        "qatar",
        "romania",
        "russia",
        "serbia",
        "sudan",
        "switzerland",
        "syria",
        "yugoslavia",
    ]
