from ..category import Category


class Element(Category):
    def get_values(self):
        return [
            "actinium",
            "aluminium",
            "americium",
            "antimony",
            "argon",
            "arsenic",
            "astatine",
            "barium",
            "beryllium",
            "boron",
            "bromine",
            "carbon",
            "cerium",
            "chlorine",
            "chromium",
            "cobalt",
            "copper",
            "fluorine",
            "gallium",
            "gold",
            "helium",
            "hydrogen",
            "indium",
            "iodine",
            "iron",
            "lead",
            "lithium",
            "mercury",
            "neon",
            "nickel",
            "nitrogen",
            "potassium",
            "promethium",
            "radon",
            "selenium",
            "silver",
            "tin",
            "titanium",
            "tungsten",
        ]
