from .category import Category


class Fabric(Category):
    _name = "fabric"
    _values = [
        "brocade",
        "burlap",
        "calico",
        "chenille",
        "chiffon",
        "corduroy",
        "cotton",
        "denim",
        "felt",
        "fishnet",
        "flannel",
        "fleece",
        "fur",
        "gaberdine",
        "gingham",
        "hessian",
        "khaki",
        "knit",
        "lace",
        "leather",
        "linen",
        "lycra",
        "organza",
        "plush",
        "satin",
        "silk",
        "spandex",
        "tartan",
        "tulle",
        "tweed",
        "velure",
        "velvet",
        "velveteen",
        "wool",
    ]
