from ..category import Category

class Festivals(Category):
    def get_values(self):
        return [
            "Alabama Hot Air Balloon festival",
            "Aloha Festivals",
            "Baisakhi",
            "Bastille Day",
            "Bhai Dooj",
            "Canberra Balloon Fiesta",
            "Chhat Puja",
            "Christmas",
            "Daffodil Festival",
            "Diwali",
            "Durga Puja",
            "Eid"
            "Esala Perahera",
            "Eurockeennes de Belfort",
            "Father's Day",
            "Festivals of Flowers",
            "Friendship Day",
            "Gion Matsuri",
            "Holi",
            "Homowo Festival",
            "Hadaka Matsuri Festival",
            "International Mango Festival",
            "Janmashtami",
            "Jidai Matsuri",
            "La Tomatina",
            "Lohri",
            "Love Parade",
            "Mahashivratri",
            "Mother's Day",
            "New Year",
            "Onam",
            "Pongal",
            "Quebec Winter Carnival",
            "Raksha Bandhan",
            "Rio de Janeiro Carnival",
            "Sahara Douz Festival",
            "Samhain Festival",
            "Teej",
            "Thanksgiving Day",
            "Up Helly Aa",
            "Valentine's Day",
            "Winterlude",
        ]
   