from .category import Category


class Fish(Category):
    _name = "fish"
    _values = [
        "albacore",
        "anchovy",
        "barracuda",
        "bass",
        "beluga",
        "blowfish",
        "bluegill",
        "bonefish",
        "bream",
        "bullhead",
        "butterfish",
        "carp",
        "catfish",
        "clownfish",
        "cod",
        "dorado",
        "eel",
        "flounder",
        "gemfish",
        "goldfish",
        "guppy",
        "gurnard",
        "haddock",
        "halibut",
        "herring",
        "lionfish",
        "loach",
        "monkfish",
        "moonfish",
        "parrotfish",
        "perch",
        "piranha",
        "pollock",
        "pufferfish",
        "ray",
        "redfin",
        "ribbonfish",
        "salmon",
        "sardine",
        "seahorse",
        "silverfish",
        "stingray",
        "stonefish",
        "sturgeon",
        "sunfish",
        "swordfish",
        "tilapia",
        "trout",
        "tuna",
        "yellowfin",
    ]
