from ..category import Category


class Flower(Category):
    def get_values(self):
        return [
            "acacia",
            "aloe",
            "azalea",
            "begonia",
            "bluebell",
            "burdock",
            "buttercup",
            "cactus",
            "camomile",
            "chrysanthemum",
            "crocus",
            "daffodil",
            "dahlia",
            "daisy",
            "dandelion",
            "foxglove",
            "geranium",
            "hemlock",
            "hibiscus",
            "hyacinth",
            "hydrangea",
            "iris",
            "jasmine",
            "lavender",
            "lily",
            "lotus",
            "lupin",
            "magnolia",
            "mandrake",
            "marigold",
            "nightshade",
            "orchid",
            "pansy",
            "passionflower",
            "peony",
            "petunia",
            "poppy",
            "primrose",
            "rose",
            "saffron",
            "samphire",
            "snapdragon",
            "snowdrop",
            "sunflower",
            "tulip",
            "valerian",,
            "violet",
            "wisteria",
        ]
