from ..category import Category


class Food(Category):
  def get_values(self):
    return [
        'apple',
        'bacon',
        'chocolate',
        'cookie',
        'egg',
        'lemon',
        'waffle',
        'grape',
        'peach',
        'mango',
        'pineapple',
        'avocado',
        'carrot',
        'potato',
        'kiwi',
        'strawberry',
        'pie',
        'pizza',
        'burger',
        'kebab',
        'noddle',
        'egg benedict',
        'fried rice',
        'banana',
        'spaghetti',
        'cabbage',
        'carpaccio',
        'sushi',
        'ramen',
        'onigiri',
        'udon',
        'sashimi',
        'curry',
        'fried chicken',
        'karaage',
        'gyoza',
        'rendang',
        'orange'
    ]
