from ..category import Category


class Food(Category):
    def get_values(self):
        return [
            "applewood",
            "avocado",
            "babybel",
            "bacon",
            "bagel",
            "bread",
            "brie",
            "camenbert", 
            "candy",
            "carrot",
            "caviar",
            "cheese",
            "chicken",
            "chocolate",
            "cookie",
            "croissant",
            "crouton",
            "donut",
            "dumpling",
            "eclair",
            "egg",
            "eggplant",
            "fries",
            "garlic",
            "gravy",
            "hashbrown",
            "icecream",
            "jelly", 
            "lasagne",
            "mozzerella",
            "muffin",
            "noodles",
            "pasty",
            "pho",
            "potato",
            "ramen",
            "ravioli",
            "rice",
            "ricotta",
            "roastie",
            "salmon",
            "sandwich",
            "sashimi",
            "sausage",
            "steak",
            "sushi",
            "toast",
            "tofu",
            "tortelloni",
            "truffle",
            "turkey",
            "waffle",
            "wotsits",
        ]
