from ..category import Category


class Geography(Category):
    def get_values(self):
        return [
            "archipelago",
            "beach",
            "canal",
            "canyon",
            "cape",
            "cave",
            "cliff",
            "cove",
            "delta",
            "dessert",
            "dune",
            "fjord",
            "forest",
            "geyser",
            "glacier",
            "gulf",
            "hill",
            "iceberg",
            "island",
            "isthmus",
            "jungle",
            "lagoon",
            "lake",
            "marsh",
            "mesa",
            "mountain",
            "nether",
            "oasis",
            "ocean",
            "peninsula",
            "plain",
            "plateau",
            "pond",
            "prairie",
            "river",
            "sea",
            "sky",
            "straight",
            "stream",
            "swamp",
            "tundra",
            "valley",
            "volcano",
            "waterfall",
        ]
