from ..category import Category


class Geography(Category):
  def get_values(self):
    return [
        'mountain',
        'ocean',
        'waterfall',
        'glacier',
        'volcano',
        'iceberg',
        'sea',
        'fjord',
        'stream',
        'geyser',
        'tundra',
        'hill',
        'cape',
        'lake',
        'valley',
        'swamp',
        'gulf',
        'lagoon',
        'jungle',
        'delta',
        'river',
        'cave',
        'plateau',
        'canyon',
        'oasis',
        'dessert',
        'dune',
        'mesa',
        'straight',
        'prairie',
        'cove',
        'cliff',
        'isthmus',
        'island',
        'archipelago',
        'peninsula',
        'beach',
        'forest',
        'marsh',
        'pond',
        'plain',
        'canal',
        'sky',
        'nether'
    ]
