from ..category import Category


class Instrument(Category):
    def get_values(self):
        return [
            "accordion",
            "bagpipes",
            "banjo",
            "bassoon",
            "bongo",
            "cello",
            "clarinet",
            "cornet",
            "cymbal",
            "didgeridoo",
            "drumkit",
            "euphonium",
            "fiddle",
            "flute",
            "glockenspiel",
            "gong",
            "guitar",
            "harmonica",
            "harmonium",
            "harp",
            "harpsichord",
            "lute",
            "mandolin",
            "melodica",
            "oboe",
            "ocarina",
            "organ",
            "piano",
            "piccolo",
            "recorder",
            "saxophone",
            "sitar",
            "synthesizer",
            "tambourine",
            "theremin",
            "timpani",
            "triangle",
            "trombone",
            "trumpet",
            "tuba",
            "ukulele",
            "viola",
            "violin",
            "xylophone",
        ]
