from .category import Category


class Scientist(Category):
    _name = "scientist"
    _values = [
        "ampere",
        "archimedes",
        "aristarchus",
        "aristotle",
        "aryabhata",
        "avogadro",
        "bernoulli",
        "bohr",
        "boyle",
        "brahmagupta",
        "chadwick",
        "chandrasekhar",
        "chargaff",
        "copernicus",
        "curie",
        "dalton",
        "darwin",
        "descartes",
        "einstein",
        "eratosthenes",
        "euclid",
        "euler",
        "faraday",
        "fermat",
        "fibonacci",
        "fisher",
        "franklin",
        "galileo",
        "gauss",
        "gibbs",
        "hawking",
        "hooke",
        "hubble",
        "kepler",
        "lavoisier",
        "lovelace",
        "maxwell",
        "mendel",
        "newton",
        "pasteur",
        "pauling",
        "planck",
        "raman",
        "rutherford",
        "thomson",
    ]
