from ..category import Category


class Scientist(Category):
    def get_values(self):
        return [
            "adalovelace",
            "alberteinstein",
            "alexanderfleming",
            "amedeoavogadro",
            "anaximander",
            "andremarieampere",
            "antoinelavoisier",
            "archimedes",
            "aristarchus",
            "aristotle",
            "aryabhata",
            "benjaminfranklin",
            "brahmagupta",
            "carlfriedrichgauss",
            "charlesdarwin",
            "cvraman",
            "danielbernoulli",
            "edwinhubble",
            "eratosthenes",
            "ernestrutherford",
            "erwinchargaff",
            "euclid",
            "fibonacci",
            "francisbacon",
            "galileogalilei",
            "gregormendel",
            "heinrichhertz",
            "isaacnewton",
            "jameschadwick",
            "jamesmaxwell",
            "jameswatt",
            "jjthomson",
            "johanneskepler",
            "johndalton",
            "leonhardeuler",
            "linuspauling",
            "louispasteur",
            "luisalvarez",
            "mariecurie",
            "maryanning",
            "maxplanck",
            "michaelfaraday",
            "neilsbohr",
            "nicolauscopernicus",
            "pierredefermat",
            "renedescartes",
            "robertboyle",
            "roberthooke",
            "ronaldfisher",
            "rosalindfranklin",
            "stephenhawking",
            "subrahmanyanchandrasekhar",
            "tychobrahe",
            "willardgibbs",
        ]
