from ..category import Category


class Scientist(Category):
    def get_values(self):
        return [
            "lovelace",
            "einstein",
            "avogadro",
            "ampere",
            "lavoisier",
            "archimedes",
            "aristarchus",
            "aristotle",
            "aryabhata",
            "franklin",
            "brahmagupta",
            "gauss",
            "darwin",
            "raman",
            "bernoulli",
            "hubble",
            "eratosthenes",
            "rutherford",
            "chargaff",
            "euclid",
            "fibonacci",
            "galileo",
            "mendel",
            "newton",
            "chadwick",
            "maxwell",
            "thomson",
            "kepler",
            "dalton",
            "euler",
            "pauling",
            "pasteur",
            "curie",
            "planck",
            "faraday",
            "bohr",
            "copernicus",
            "fermat",
            "descartes",
            "boyle",
            "hooke",
            "fisher",
            "hawking",
            "chandrasekhar",
            "gibbs",
        ]
