from ..category import Category


class Spice(Category):
    def get_values(self):
        return [
            "aniseed",
            "basil",
            "bayleaf",
            "cardamom",
            "cayenne",
            "chicory",
            "chilli",
            "chive",
            "cinnamon",
            "clove",
            "coconut",
            "coriander",
            "cress",
            "cumin",
            "curry",
            "dill",
            "fennel",
            "garlic",
            "ginger",
            "horseradish",
            "marjoram",
            "mint",
            "miso",
            "mustard",
            "nutmeg",
            "oregano",
            "paprika",
            "parsley",
            "pepper",
            "peppercorn",
            "rosemary",
            "saffron",
            "sage",
            "salt",
            "sesame",
            "soy",
            "tansy",
            "tarragon",
            "thyme",
            "turmeric",
            "wasabi",
        ]
