from ..category import Category

class State(Category):
    def get_values(self):
        return [
            "alabama",
            "alaska",
            "arkansas",
            "california",
            "colorado",
            "connecticut",
            "delaware",
            "florida",
            "georiga",
            "hawaii",
            "idaho",
            "illinois",
            "indiana",
            "iowa",
            "kansas",
            "kentucky",
            "louisiana",
            "maine",
            "maryland",
            "massachusetts",
            "michigan",
            "minnesota",
            "mississippi",
            "missouri",
            "montana",
            "nebraska",
            "nevada",
            "ohio",
            "oklahoma",
            "oregon",
            "pennsylvania",
            "tennessee",
            "texas",
            "utah",
            "vermont",
            "virginia",
            "washington",
            "wisconsin",
            "wyoming",
        ]
