from .category import Category


class Vegetable(Category):
    _name = "vegetable"
    _values = [
        "ackee",
        "asparagus",
        "aubergine",
        "beetroot",
        "broccoli",
        "cabbage",
        "carrot",
        "cauliflower",
        "celeriac",
        "celery",
        "chard",
        "chive",
        "corn",
        "courgette",
        "cress",
        "cucumber",
        "eggplant",
        "fennel",
        "gherkin",
        "horseradish",
        "kale",
        "leek",
        "lettuce",
        "marrow",
        "onion",
        "parsnip",
        "potato",
        "radish",
        "shallot",
        "spinach",
        "squash",
        "swede",
        "turnip",
        "yam",
        "zucchini",
    ]
