from ..category import Category


class Vehicle(Category):
    _name = "vehicle"
    _values = [
        "aeroplane",
        "bicycle",
        "boat",
        "bulldozer",
        "bus",
        "canoe",
        "car",
        "chariot",
        "coach",
        "crane",
        "cycle",
        "ferry",
        "forklift",
        "freighter",
        "helicopter",
        "hovercraft",
        "jet",
        "jetski",
        "lorry",
        "motorbike",
        "rickshaw",
        "rocket",
        "rollerskates",
        "scooter",
        "ship",
        "skateboard",
        "snowmobile",
        "spaceship",
        "steamroller",
        "submarine",
        "tanker",
        "taxi",
        "toboggan",
        "tractor",
        "train",
        "tricycle",
        "truck",
        "unicycle",
        "van",
        "yacht",
    ]
