from ..categories import *
from .collection import Collection

class All(Collection):
    _name = "all"
    _categories = [
        Adjective,
        Animal,
        Atmosphere,
        Author,
        Bird,
        Book,
        Brand,
        Bread,
        Cake,
        Capital,
        City,
        Clothing,
        Color,
        Constellation,
        Country,
        Cuisine,
        Currency,
        Dog,
        Drink,
        Electronic,
        Element,
        Emotion,
        Festivals,
        Film,
        Fish,
        Flower,
        Food,
        Fruit,
        Gem,
        Geography,
        Instrument,
        Language,
        Music,
        OperatingSystem,
        Particle,
        Planet,
        Pokemon,
        Profession,
        ProgrammingLanguage,
        RandomId,
        Scientist,
        SearchEngine,
        Shape,
        Spice,
        Sport,
        State,
        Tea,
        Tool,
        Utensil,
        Vegetable,
        Vehicle,
        Weather,
        Wine,
    ]
